spring:
  application:
    name: mcp-server-computer
  ai:
    mcp:
      server:
        ${spring.application.name}}

  main:
    banner-mode: off
    web-application-type: none

logging:
  pattern:
    console:
  file:
    name: ${spring.application.name}.log

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true