csdn:
  api:
    categories: Java面试
    cookie: uuid_tt_dd=10_37481455750-1729751714749-504789; fid=20_97353541075-1729751715758-294666; UN=qq_62566185; c_dl_um=-; ssxmod_itna=YqGx2CD=iti=6xBab8DyDI2GoqLP0KiDCKwiDNxBuAo4iNDnD8x7YDv+ITKo+3KnG0Ydfe+gemxfFQ8OdqduQbPKf/mDAoDhx7QDox0=DnxAQDj1R5GGUxBYDQxAYDGDDpcDGdVgRD7hU9+LUj3kj6twtDmfj0DGjRDitoxivDyLNSR8DSDDfYxB=DxAf0D7Ul3LdDbqDuF6Q5EqDLmnnax=QDbrPyDPWDtdT2S4DHUTN/3TyYBA3slODT8GP=KOheYDqibY+QtGmb/2+PC0w4fY4jWXTemDdxD=; ssxmod_itna2=YqGx2CD=iti=6xBab8DyDI2GoqLP0KiDCKwiDx8d=xqGXIpPGaU0I6KC5IE5yLO79XkYSgfYXsFIgg7+8iVxciwhUAzk8nvCVon32G56FAoxHnBQd2NzP1oWYAB=qFst/UlKnDAidD+G8nxmOKCGXtjKne80PfkiPpnpxxAPh07ROYOddaRPIjW37I2R+ikeT=mtwjmoY=iAHXRDzjWcXUxuxp=U1EEc1p69OEoFGLZRCd1nwWcbqV20AX+8qhmKdZxoTcfbTgo9PMTvh2EOz4WnkGeSX1PWqnKM1UQj1eaS1A93Y27HWx=LgWC4oHbYVkiWRFdR=Fgr9uts2im+o+dtXrOuDzixFrfo70NihbWqWFxTHrWG8pHg1fQCc4p/dtAlwKG8QoiKD3BSYk0WCLhkMvuRYVD85=WIfhVDp=ebZj3HgFlmfzw5KB5Yn3XGLu0NHSwEmHAwjKxbs3AHgbGSbbdPD7QnDGcDG7eiDD==; tfstk=fQjmYciizQGCr-ukEz-b7EAzOpz8cxt6F1n96hdazQR7ChKADaAGQ6897OeXQ_XFtthOkOC-4Kpiuq8Z0U5l6OnOHS1tj_fCtcefk1dNZdp6Qf8Z0YoyQn81kCdvshX1t8FLvkBfhhtY9WEK4ErGWhOaXhoFRe2ebWFL2j6L8axNMKJo60XyNdmq0m5Za4RW3q-wgFlrzpRybC5wg4oyKK0Z_mRaETRWQhRwzKPJMIR14SKacrzXpIIknUzR3QrRIgvDoBWVmcoZ8KYDTtRzOy3VbFfDogEmOKbPKspc1kiX0FbV8nSgtoxPdaC2E1PnSQ7hcGYdmW0BgiO1tn7uamxwcibpRh4nhLIcUMTGcSmyi_6PJnsUNcfFe9IXPGVnaC_vd3JcrRuygFSPJ4uEP1i6URIr5VT2FLAplDeKBiqoonwuE2JDuL9q282o5oY2FLALE80UUEJW30C..; c_dl_prid=1729940610285_805792; c_dl_rid=1732784233297_469772; c_dl_fref=https://blog.csdn.net/u011418943; c_dl_fpage=/download/u011418943/10292537; _ga_JJBD2VG1H7=GS1.1.1735717971.5.1.1735718001.30.0.0; __gads=ID=c049149542f2f9bb:T=1729751984:RT=1739977742:S=ALNI_MbRee4m0F3oEH2FdzN8DBvdZoayQg; __gpi=UID=00000f519bf181af:T=1729751984:RT=1739977742:S=ALNI_MYfcEWPKeu_uJ3Ai2GVgfGHIhh8ow; FCNEC=%5B%5B%22AKsRol9FUVYeTcxbbXyoxJdv5rVAkYE_m04f5xZuBmmfL5Sw76J27I4yc7GRe4YFSzFnXCbtjBd3GOsQ9xlMiQPQllQVR5ypmg9DEpZe3EwjsJF6Ct6OJY67l-iL6z4vkcd8ZxhC3KpBff4onWRzamLjYB40wk_msw%3D%3D%22%5D%5D; Hm_lvt_6bcd52f51e9b3dce32bec4a3997715ac=1744870581,1744905863,1744948353,1745148516; _ga=GA1.2.2057609489.1729751718; _clck=12dq8y1%7C2%7Cfv8%7C0%7C1758; _ga_7W1N0GEY1P=GS1.1.1745148516.342.1.1745148563.13.0.0; c_adb=1; is_advert=1; hide_login=1; c_first_ref=www.google.com; c_segment=5; dc_sid=bb9ec563dea150944ae4ecd9134df548; creative_btn_mp=3; loginbox_strategy=%7B%22taskId%22%3A317%2C%22abCheckTime%22%3A1745637900950%2C%22version%22%3A%22ExpA%22%2C%22nickName%22%3A%22%E7%A9%BA%E7%99%BD%E6%97%A0%E4%B8%8A%22%2C%22blog-threeH-dialog-expa%22%3A1745564276271%7D; dc_session_id=10_1745649305226.244313; c_first_page=https%3A//www.csdn.net/; c_dsid=11_1745649305584.813010; c_page_id=default; c-sidebar-collapse=0; c_ab_test=1; SESSION=63dfae3b-29e7-485a-9a52-20b6a8a92b9a; UserName=qq_62566185; UserInfo=98fc5a658c9649f6aaf7c9ede4d42395; UserToken=98fc5a658c9649f6aaf7c9ede4d42395; UserNick=%E7%A9%BA%E7%99%BD%E6%97%A0%E4%B8%8A; AU=40A; BT=1745649322721; p_uid=U010000; creativeSetApiNew=%7B%22toolbarImg%22%3A%22https%3A//img-home.csdnimg.cn/images/20230921102607.png%22%2C%22publishSuccessImg%22%3A%22https%3A//img-home.csdnimg.cn/images/20240229024608.png%22%2C%22articleNum%22%3A1%2C%22type%22%3A2%2C%22oldUser%22%3Atrue%2C%22useSeven%22%3Afalse%2C%22oldFullVersion%22%3Atrue%2C%22userName%22%3A%22qq_62566185%22%7D; csdn_newcert_qq_62566185=1; c_pref=https%3A//www.google.com/; c_ref=https%3A//www.csdn.net/; log_Id_pv=4; log_Id_view=125; dc_tos=svbbol; log_Id_click=6

spring:
  application:
    name: mcp-server-csdn

  ai:
    mcp:
      server:
        name: ${spring.application.name}
        version: 1.0.0

  main:
    banner-mode: off

# stdio 模式打开，sse 模式，注释掉。
    web-application-type: none


logging:
  # stdio 模式打开，sse 模式，注释掉。
  pattern:
    console:
  file:
    name: data/log/${spring.application.name}.log

server:
  port: 8101
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

